### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-1-evaluacion-intermedia-2y2son4#1]
Muy buen trabajo @2y2son4!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 282 / 347
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos al menos una etiqueta `ul`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `li` en el menú.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menú, dentro de los `li`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { display: flex }`
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by 2y2son4** [comment]
¡Listo, muchas gracias por la corrección! 
Solo un apunte respecto a los estilos repetidos en la mediaquery en CSS: el `display: flex` estaba dentro de un comentario explicando justamente porqué no tenía que aparecer en la mediaquery, para yo irme quedando con la copla de cómo funcionan, pero lo he quitado para que no vuelva a aparecer como un issue.

**Comment by igarridomorillas** [comment]
No tengo claro que fuera eso. Creo que me lo ha chivado el autocorrector por el `display: flex;` que está repe en el `.header` fuera del media-query y el `.header` del media-query

**Comment by 2y2son4** [comment]
¡Ya sé que ha pasado! Durante la corrección de Dayana me lo puse en un comentario con la explicación, pero en el último commit estaba repetido. ¡Ups! 😅
